### PR TITLE
Create correction of reflection

### PR DESCRIPTION
**Pull request by akubosylva**
I went through your original code and tried to work out something for the removal of reflections.
Please go through it and try to integrate the code to your original code base so we see how it works
Sorry I didn't integrate it myself, I'm working on a lot of things right now. You can get back to me via twitter.
Thank you

### CODE REVIEW

**Comment by drewroberts** [comment]
This is great. I'll send you the $1k bounty in ETH. You da man!

**Comment by drewroberts** [comment]
You knocked out #1 #3 #4 #8 #11 #12

**Comment by drewroberts** [comment]
I owe you $6k in bounties. Thank you fren

**Comment by akubosylva** [comment]
Thanks man
Anytime
I'm up for work anytime you need me

**Comment by akubosylva** [comment]
Hey man
How are you
Haven't heard anything from you concerning the pay
Really

**Pull request merged**
